### ISSUE TITLE
Adapt `x/btcstaking` unit tests to pre-approval flow

### ISSUE THREAD

**Issue by KonradStaniec** [babylonlabs-io/babylon#119]
after: https://github.com/babylonlabs-io/babylon/pull/117

Most `x/btcstaking` tests still assume old flow. We need to adapt them to new flow, and test both paths. This is also good ocasion to refactor `x/btcstaking` message handlers

**Comment by SebastianElvis** [comment]
Since we are doing this, what do you think about merging the test util under `x/btcstaking` with the test framework at https://github.com/babylonlabs-io/babylon/blob/544386204a860ee7159923b3d34174d0cf8c6049/testutil/helper, and use this framework for testing everything? This way we get rid of many mock tests

**Comment by KonradStaniec** [comment]
you mean get rid of https://github.com/babylonlabs-io/babylon/blob/main/x/btcstaking/keeper/keeper_test.go#L30 ? Tbh sounds great 👍
